notifications:
  email:
    on_success: never
    on_failure: change

os: linux

language: android

cache:
  timeout: 600
  directories:
    - node_modules

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-24
    # - extra-google-m2repository
    # - extra-android-m2repository

jdk:
  - oraclejdk8

before_install:
  - echo "Before Install stage"
  - ls -l ${ANDROID_HOME}licenses
  - cat ${ANDROID_HOME}licenses/android-sdk-license
  # - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 >> ${ANDROID_HOME}licenses/android-sdk-license

install:
  - echo "Install stage"
  - nvm ls
  - nvm install 6
  - nvm use 6
  # - curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
  # - sudo apt-get install -y python-software-properties nodejs
  - npm install -g npm ionic cordova
  - npm prune
  - npm install

script:
  - echo "Start Linting"
  - npm test
  - echo "Start Build Test"
  - npm run build
  - echo "Cordova Build Android Test"
  - ionic cordova build android

after_success:
  - echo "Build Success"

after_failure:
# What if your test fails?
- echo "After failure stage"
- ionic info
