notifications:
  email:
    on_success: never
    on_failure: change

os: linux

language: node_js
node_js:
  - "7"

cache:
  timeout: 600
  directories:
    - node_modules

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-22

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22
    # - sys-img-armeabi-v7a-android-17

install:
  - npm install -g npm ionic cordova
  - npm prune
  - npm install

script:
  - npm run build

after_success:
  - ionic cordova build android
